# Build ctir clang.

language: minimal

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
      addons:
        apt:
          update: true
          packages:
            - clang-9
            - cmake
    - os: osx
      osx_image: xcode11.5
      addons:
        homebrew:
          packages:
            - llvm@9
