language: shell
jobs:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          update: true
          packages:
            - clang-9
            - cmake
            - zip
      env: CC=clang-9 CXX=clang++-9
    - os: osx
      osx_image: xcode11.5
      addons:
        homebrew:
          packages:
            - llvm@9
            - cmake
            - zip
      env: CC=clang CXX=clang++

script: >
  mkdir build;
  cd build;
  cmake ../llvm -DCMAKE_BUILD_TYPE=MinSizeRel -DLLVM_ENABLE_PROJECTS=clang -DLLVM_TARGETS_TO_BUILD="" -G "Unix Makefiles";
  make clang -j8
